Repository 8tTruck/StudyGaemi, pull requests merged in 2024-07, with the labels that each got.

#73 [Design] UserView 수정
  StudyGaemi/Controllers/BottomSheetViewController.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Views/Setting/BottomSheetView.swift
  StudyGaemi/Views/Setting/MemberInfoView.swift
  StudyGaemi/Views/Setting/PrivacyPolicyView.swift
  StudyGaemi/Views/Setting/SettingView.swift
Labels: Design

#74 알람기능 버그 및 리팩토링
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Controllers/AlarmCoreDataManager.swift
  StudyGaemi/Controllers/AlarmResultController.swift
  StudyGaemi/Controllers/AlarmSettingController.swift
  StudyGaemi/Controllers/AudioController.swift
  StudyGaemi/Models/AlarmModel.swift
  StudyGaemi/SceneDelegate.swift
  StudyGaemi/Views/Alarm/AlarmQuestionView.swift
  StudyGaemi/Views/Alarm/AlarmResultView.swift
  StudyGaemi/Views/Alarm/AlarmSettingView.swift
  StudyGaemi/Views/Alarm/AlarmViewController.swift
  StudyGaemi/Views/CustomButton.swift
  StudyGaemi/Views/CustomTextField.swift
Labels: Design, Fix, Delete, Merge

#77 디자인 수정 및 알람에러 예외처리 및 Alert 추가
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Controllers/AlarmCoreDataManager.swift
  StudyGaemi/Controllers/AlarmDelegate.swift
  StudyGaemi/Controllers/AlarmSettingController.swift
  StudyGaemi/Controllers/SettingTimerVC.swift
  StudyGaemi/Views/Alarm/AlarmSettingView.swift
  StudyGaemi/Views/Alarm/AlarmViewController.swift
Labels: Feat, Design, Fix, Merge

#80 develop to main(v1.0.2)
  README.md
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/xcshareddata/xcschemes/StudyGaemi.xcscheme
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Controllers/AlarmCoreDataManager.swift
  StudyGaemi/Controllers/AlarmDelegate.swift
  StudyGaemi/Controllers/AlarmResultController.swift
  StudyGaemi/Controllers/AlarmSettingController.swift
  StudyGaemi/Controllers/AudioController.swift
  StudyGaemi/Controllers/BottomSheetViewController.swift
  StudyGaemi/Controllers/CircularTimerVC.swift
  StudyGaemi/Controllers/SettingTimerVC.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Models/AlarmModel.swift
  StudyGaemi/SceneDelegate.swift
  StudyGaemi/Views/Alarm/AlarmQuestionView.swift
  StudyGaemi/Views/Alarm/AlarmResultView.swift
  StudyGaemi/Views/Alarm/AlarmSettingView.swift
  StudyGaemi/Views/Alarm/AlarmViewController.swift
  StudyGaemi/Views/Calendar/CalendarViewController.swift
  StudyGaemi/Views/CustomButton.swift
  StudyGaemi/Views/CustomTextField.swift
  StudyGaemi/Views/Login/CreateAccountSuccessViewController.swift
  StudyGaemi/Views/Login/CreateAccountViewController.swift
  StudyGaemi/Views/Login/EmailConfirmViewController.swift
  StudyGaemi/Views/Login/LoginViewController.swift
  StudyGaemi/Views/Login/MakePasswordViewController.swift
  StudyGaemi/Views/Setting/BottomSheetView.swift
  StudyGaemi/Views/Setting/BugReportView.swift
  StudyGaemi/Views/Setting/MemberInfoView.swift
  StudyGaemi/Views/Setting/PrivacyPolicyView.swift
  StudyGaemi/Views/Setting/SettingView.swift
  StudyGaemi/Views/Study/CircularTimerView.swift
  StudyGaemi/Views/Study/TimerResultViewController.swift
Labels: Merge
