Repository 8tTruck/StudyGaemi, pull requests merged in 2024-06, with the labels that each got.

#5 공용 CustomButton,TextField 및 빈화면 터치 시 keyboard 내려가는 기능 추가
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Views/AlarmViewController.swift
  StudyGaemi/Views/BaseViewController.swift
  StudyGaemi/Views/CustomButton.swift
  StudyGaemi/Views/CustomTextField.swift
Labels: Feat, Design, Merge

#6 머지 부탁드립니다!
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Assets.xcassets/Image/Contents.json
  StudyGaemi/Assets.xcassets/Image/alarmButton.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Image/alarmButton.imageset/alarmButton.svg
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Views/AlarmButton.swift
  StudyGaemi/Views/AlarmSettingView.swift
  StudyGaemi/Views/AlarmViewController.swift
Labels: Feat, Design, Merge

#7 [Feat개ME TableView 생성
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat

#10 Jiyeondu/monthly UI
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StudyGaemi.xcodeproj/xcshareddata/xcschemes/StudyGaemi.xcscheme
  StudyGaemi/Views/BadgeViewCell.swift
  StudyGaemi/Views/CalendarViewController.swift
Labels: Feat, Design, Merge

#14 Feat: CustomAlertView
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Assets.xcassets/Stamp/Contents.json
  StudyGaemi/Assets.xcassets/Stamp/studyStamp.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Stamp/studyStamp.imageset/Layer 2-1 1.png
  StudyGaemi/Views/AlertView.swift
  StudyGaemi/Views/BadgeViewCell.swift
  StudyGaemi/Views/CalendarCell.swift
  StudyGaemi/Views/CalendarViewController.swift
Labels: Feat, Design, Merge

#15 [Add]각 화면 UI구성
  StudyGaemi.xcodeproj/xcshareddata/xcschemes/StudyGaemi.xcscheme
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat, Design

#20 Origin/taeng/setting page3
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Views/AnnouncementViewController.swift
  StudyGaemi/Views/BottomSheetViewController.swift
  StudyGaemi/Views/BugReportViewController.swift
  StudyGaemi/Views/MemberInfoViewController.swift
  StudyGaemi/Views/PrivacyPolicyViewController.swift
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat, Design

#23 Jiyeondu/monthly UI
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/xcshareddata/xcschemes/StudyGaemi.xcscheme
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Assets.xcassets/Stamp/perfectStamp.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Stamp/perfectStamp.imageset/Rectangle (1).pdf
  StudyGaemi/Assets.xcassets/Stamp/wakeupStamp.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Stamp/wakeupStamp.imageset/Rectangle.pdf
  StudyGaemi/Models/Data.swift
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Models/User.swift
  StudyGaemi/Views/CalendarCell.swift
  StudyGaemi/Views/CalendarViewController.swift
Labels: Feat, Fix, Merge

#24 머지 부탁드립니다.
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/xcuserdata/t2023-m0056.xcuserdatad/xcschemes/Copy of StudyGaemi.xcscheme
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Controllers/AlarmCoreDataManager.swift
  StudyGaemi/Controllers/AlarmQuestionController.swift
  StudyGaemi/Controllers/AlarmSettingController.swift
  StudyGaemi/Controllers/AudioController.swift
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Info.plist
  StudyGaemi/SceneDelegate.swift
  StudyGaemi/StudyGaemi.xcdatamodeld/StudyGaemi.xcdatamodel/contents
  StudyGaemi/Views/AlarmQuestionView.swift
  StudyGaemi/Views/AlarmResultView.swift
  StudyGaemi/Views/AlarmSettingView.swift
  StudyGaemi/Views/AlarmViewController.swift
Labels: Feat, Fix, Merge

#25 [Feat] FirestoreManager 추가함 CRUD 기능 #2
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Controllers/AlarmQuestionController.swift
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Models/Data.swift
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Models/StudyModel.swift
  StudyGaemi/Models/UserModel.swift
  StudyGaemi/Models/WakeUpModel.swift
  StudyGaemi/Views/AlarmQuestionView.swift
  StudyGaemi/Views/CalendarViewController.swift
  StudyGaemi/Views/EmailConfirmViewController.swift
  StudyGaemi/Views/MakePasswordViewController.swift
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat, Fix, Delete, Remove, Merge

#27 Jiyeondu/monthly UI
  StudyGaemi/Views/CalendarViewController.swift
Labels: Fix, Merge

#28 [Feat]로그아웃, 회원탈퇴, 비밀번호 변경
  StudyGaemi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Views/AnnouncementViewController.swift
  StudyGaemi/Views/BugReportViewController.swift
  StudyGaemi/Views/MemberInfoViewController.swift
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat

#31 [Feat] 애플 로그인 추가
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Info.plist
  StudyGaemi/StudyGaemi.entitlements
  StudyGaemi/Views/LoginViewController.swift
  StudyGaemi/Views/MakePasswordViewController.swift
Labels: Feat, Merge

#33 [Feat] e-mail, nickname 추가
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Views/BottomSheetViewController.swift
  StudyGaemi/Views/BugReportViewController.swift
  StudyGaemi/Views/MemberInfoViewController.swift
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat

#35 Jiyeondu/monthly UI
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/Assets.xcassets/Ant/bookAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/bookAnt.imageset/Layer 4 123 1 (1).pdf
  StudyGaemi/Assets.xcassets/Ant/failAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/failAnt.imageset/image 55 1.pdf
  StudyGaemi/Assets.xcassets/Ant/heartAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/heartAnt.imageset/Rectangle (2).pdf
  StudyGaemi/Assets.xcassets/Ant/kingAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/kingAnt.imageset/Layer 222 1.pdf
  StudyGaemi/Assets.xcassets/Ant/mainAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/mainAnt.imageset/Layer 1 1@2x 1 (1)2 1.pdf
  StudyGaemi/Views/CalendarViewController.swift
  StudyGaemi/Views/SettingViewController.swift
  StudyGaemi/Views/TimerResultViewController.swift
Labels: Feat, Design, Merge

#37 [Feat] 알림 ON/OFF 기능 추가 #2
  StudyGaemi/Controllers/AlarmController.swift
  StudyGaemi/Controllers/AlarmSettingController.swift
  StudyGaemi/Views/AlarmQuestionView.swift
  StudyGaemi/Views/AlarmSettingView.swift
  StudyGaemi/Views/AlarmViewController.swift
  StudyGaemi/Views/SettingViewController.swift
Labels: Feat, Fix, Delete, Merge

#42 [Fix] Firebase 데이터베이스 계정생성 수정
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Models/StudyModel.swift
  StudyGaemi/Models/UserModel.swift
  StudyGaemi/Models/WakeUpModel.swift
  StudyGaemi/Views/AlarmQuestionView.swift
  StudyGaemi/Views/LoginViewController.swift
  StudyGaemi/Views/MakePasswordViewController.swift
Labels: Feat, Fix, Delete, Merge

#44 [Feat] alertView
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StudyGaemi.xcodeproj/xcshareddata/xcschemes/StudyGaemi.xcscheme
  StudyGaemi/Controllers/AlarmResultController.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Models/AlertModel.swift
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Views/CalendarViewController.swift
  StudyGaemi/Views/LoginViewController.swift
  StudyGaemi/Views/TimerResultViewController.swift
Labels: Feat, Fix, Merge

#45 [Feat] 닉네임, 공부데이터 추가
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Views/SettingView.swift
Labels: Feat, Merge

#46 [Feat] 카카오 로그인, 로그아웃, 탈퇴 기능 추가 #2
  .gitignore
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi/AppDelegate.swift
  StudyGaemi/Assets.xcassets/Study/Contents.json
  StudyGaemi/Assets.xcassets/Study/Pause.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Study/Pause.imageset/pauseIcon 1.pdf
  StudyGaemi/Assets.xcassets/Study/Pause.imageset/pauseIcon 2.pdf
  StudyGaemi/Assets.xcassets/Study/Pause.imageset/pauseIcon.pdf
  StudyGaemi/Assets.xcassets/Study/Resume.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Study/Resume.imageset/resumeIcon 1.pdf
  StudyGaemi/Assets.xcassets/Study/Resume.imageset/resumeIcon 2.pdf
  StudyGaemi/Assets.xcassets/Study/Resume.imageset/resumeIcon.pdf
  StudyGaemi/Assets.xcassets/Study/Stop.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Study/Stop.imageset/stopIcon 1.pdf
  StudyGaemi/Assets.xcassets/Study/Stop.imageset/stopIcon 2.pdf
  StudyGaemi/Assets.xcassets/Study/Stop.imageset/stopIcon.pdf
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Controllers/CircularTimerVC.swift
  StudyGaemi/Controllers/DatePickerModalVC.swift
  StudyGaemi/Controllers/SettingTiemrVC.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Info.plist
  StudyGaemi/RepeatingSecondsTimer.swift
  StudyGaemi/SceneDelegate.swift
  StudyGaemi/UIColor+Extensions.swift
  StudyGaemi/Views/CircularTimerView.swift
  StudyGaemi/Views/LoginViewController.swift
Labels: Feat, Fix, Merge

#47 [Merge] 프로필 사진 추가
  StudyGaemi/Assets.xcassets/Ant/profileAnt.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Ant/profileAnt.imageset/Frame 10631.pdf
  StudyGaemi/Assets.xcassets/Ant/profileAnt.imageset/Mask group.pdf
  StudyGaemi/Views/SettingView.swift
Labels: Merge

#49 [Fix] 카카오톡으로 로그인 안되는 현상 수정 해결 후 머지 요청드립니다.
  StudyGaemi/Controllers/AlarmCoreDataManager.swift
  StudyGaemi/Controllers/AuthenticationManager.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Info.plist
  StudyGaemi/Models/FirestoreManager.swift
  StudyGaemi/Views/LoginViewController.swift
Labels: Fix, Merge

#50 [Design] 부분수정
  StudyGaemi/Controllers/BugReportViewController.swift
  StudyGaemi/Controllers/MemberInfoViewController.swift
  StudyGaemi/Views/AnnouncementView.swift
  StudyGaemi/Views/MemberInfoView.swift
  StudyGaemi/Views/PrivacyPolicyView.swift
  StudyGaemi/Views/SettingView.swift
Labels: Design

#52 rootView 전환 시 튕기는 현상 수정
  StudyGaemi/Controllers/CircularTimerVC.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Info.plist
  StudyGaemi/RepeatingSecondsTimer.swift
Labels: Feat, Fix, Delete, Merge

#56 [Design] UI수정
  StudyGaemi/Assets.xcassets/Setting/Contents.json
  StudyGaemi/Assets.xcassets/Setting/editButton.imageset/Contents.json
  StudyGaemi/Assets.xcassets/Setting/editButton.imageset/fi_edit-3.pdf
  StudyGaemi/Controllers/BottomSheetViewController.swift
  StudyGaemi/Controllers/MemberInfoViewController.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Views/AnnouncementView.swift
  StudyGaemi/Views/BottomSheetView.swift
  StudyGaemi/Views/BottomTabBarViewController.swift
  StudyGaemi/Views/BugReportView.swift
  StudyGaemi/Views/PrivacyPolicyView.swift
  StudyGaemi/Views/SettingView.swift
Labels: Design

#63 [Feat] 셀에 아이콘 추가!
  StudyGaemi.xcodeproj/project.pbxproj
  StudyGaemi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StudyGaemi/Controllers/AnnouncementViewController.swift
  StudyGaemi/Controllers/MemberInfoViewController.swift
  StudyGaemi/Controllers/SettingViewController.swift
  StudyGaemi/Info.plist
  StudyGaemi/Views/Setting/ImageHelper.swift
  StudyGaemi/Views/Setting/SettingTableViewCell.swift
  StudyGaemi/Views/Setting/SettingView.swift
Labels: Feat
